### ISSUE TITLE
Video attachments are empty using type "video/quicktime" [iOS]

### ISSUE THREAD

**Issue by pauval08** [devin-la/ionic-video-chat-v2-issues#60]
In iOS the video attachments were showing up blank in my messages screen until I changed the type to "video/mp4" - then the video preview was correctly rendered.  I modified my version to save video type as "video/mp4" - maybe it is browser-dependent.

**Comment by pauval08** [comment]
Closing this issue - the problem was that the thumbnail is not yet implemented and the user must press and hold the message to see the rendering, either quicktime or mp4 is correctly detected by the browser.

**Comment by arzynik** [comment]
Thanks for the report. The latest version of the server also saves it as video/mp4 instead of quicktime. 

refs:

- https://github.com/devin-la/ionic-video-chat-v2-issues/issues/53
- https://github.com/devin-la/ionic-video-chat-server/commit/f089dde4c6bf5ae7586ebe265b18a5613a2c7ee2#diff-78c12f5adc1848d13b1c6f07055d996eR575
