### ISSUE TITLE
who to config the server

### ISSUE THREAD

**Issue by irandng** [devin-la/ionic-video-chat-v2-issues#66]
hi 
i read all of your wiki
but i want to now what the plugin must install to server for example i must install mangodb and node js
what the os is best for server
what the coment i must run on my server to install server side on my server from 0 to 100
how can i istall STUN TURN on my server 
i want run this on centos server but i can change the os 
PLZ help me

**Comment by arzynik** [comment]
For the server, you might want to try getting it running on heroku first since it should only take a few clicks.

It requires mongodb, nodejs, and npm. The npm/node dependencies are listed in the package.json. To install mongodb and nodejs, their respective websites have installers for whatever is you are using and instructions.

I developed it locally on macOS, but I have run it successfully on several different Linux builds. I also have seen other people run it on windows with no issue. It will for sure run on centos without issue. Follow the instructions on the nodejs and mongo site to install the packages manually, as the centos packages tend to be outdated, at least for the nodejs package.

I don't currently have instructions on how to run your own stun/turn server, as that's a bit more complex, but I have heard great things about 

https://github.com/coturn/coturn

If you do setup your own coturn, I'd love to hear about how you did it.
