### ISSUE TITLE
login page not showing after ionic serve

### ISSUE THREAD

**Issue by rollievillaflor** [devin-la/ionic-video-chat-v2-issues#71]
app does not show the login or the chat screen after running 'ionic serve'.  Using the v2 bundle.
https://www.evernote.com/l/AkyHGHMb4JFHIY6Hcy_Vx1OKI9dIU0vEc3E

**Comment by arzynik** [comment]
This is likly due to it not connecting to the socket server.

- Try checking out the console and see if there is an error.
- Make sure you have correctly defined **server** in your config https://github.com/devin-la/ionic-video-chat-v2-issues/wiki/Config
- And make sure you have your server up and running https://github.com/devin-la/ionic-video-chat-v2-issues/wiki/Server

**Comment by Gcchao** [comment]
how to you fix this? I turn off all everything on config.ts and server is running, but still nothing.
It just pop some statement like 

W
[21:19:38]  tslint: .../Desktop/ionic-video-chat-bundle/ionic-video-chat-v2-2.2.0/src/services/video.ts, line: 5
            Unused import: 'Events'

       L4:  import { Platform } from 'ionic-angular';
       L5:  import { Events } from 'ionic-angular';

[21:19:38]  tslint: .../Desktop/ionic-video-chat-bundle/ionic-video-chat-v2-2.2.0/src/services/video.ts, line: 51
            Unused variable: 'getDevices'

      L50:  };
      L51:  var getDevices = () => {
      L52:      navigator.mediaDevices.enumerateDevices().then(data => {

[21:19:38]  tslint: ...c/Desktop/ionic-video-chat-bundle/ionic-video-chat-v2-2.2.0/src/services/chat.ts, line: 176
            Unused variable: 'self'

     L175:  get(chatId) {
     L176:      let self = this;

**Comment by Gcchao** [comment]
Runtime Error
Error in ./AccountPage class AccountPage - caused by: Cannot read property 'name' of null
